config/routes.rb
Rails.application.routes.draw do
  #根路径为welcome/index页面
  root 'welcome#index'

  get 'welcome/index'
  get 'welcome/show_topics'
  get 'welcome/show_comments'

  resources :users
  resources :sessions, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
require 'mechanize'
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
#初始化Ruby China登录页面url
  LOGIN_URI = 'https://ruby-china.org/account/sign_in'

#用来显示登陆后的页面(没有经过格式化,显示较粗糙)
  def index
  end

#打开登陆页面
  def new
    begin
      #使用Mechanize获取ruby china登陆页面的信息，得到login_page实例
      login_page = Mechanize.new.get(LOGIN_URI)
      $logined_page = login_page
    rescue => e
      redirect_to new_session_path
    end
  end

#登录
  def create
    begin
      params[:notice] = []  #用来记录登录后的返回信息
      login_form = $logined_page.forms.last  #登录页面只有搜索和用户登录两个表单，所以取最后一个表单
      #插入相应值
      login_form.fields[1].value = params[:email]
      login_form.fields[2].value = params[:password]
      #向Ruby China提交登录表单
      logined_page = login_form.submit
      logger.info logined_page.body
      #将返回的页面body元素赋于params[:notice]方便index显示登录成功或者失败的页面
      params[:notice] << logined_page.body
      render :index
    rescue => e
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#初始化Ruby China注册页面url
  SIGN_UP_URI = 'https://ruby-china.org/account/sign_up'

#用来显示注册后的页面(没有经过格式化,显示较粗糙)
  def index
  end

#用户注册
  def new
    begin
      #使用Mechanize获取ruby china注册页面的信息，得到sign_in_page实例
      sign_in_page = Mechanize.new.get(SIGN_UP_URI)
      #为保证获取注册页面时的验证码和提交注册表单后的验证码一致，使用全局变量$page(一般不建议使用全局变量)将sign_in_page实例保存下来供create动作使用
      $page = sign_in_page
      #将获取的注册页面的验证码图片赋值给@image_url传给前台注册页面使用
      #在全自动爬虫处理应该使用图片识别插件识别验证码图片中的符号并自动填入，时间较紧没有实现，索性把图片取出来供注册使用
      @image_url = sign_in_page.search("img.rucaptcha-image")[0].attr('src')
    rescue => e
      redirect_to "/"
    end
  end

#此处是注册的另一种实现方法，原理类似，只是都放在new里处理了，但是很遗憾，两种方法都返回验证码错误,
#ruby china验证码应该是用js刷新的，所以获取或刷新注册页面的时候验证码没有对应上，暂时没有更多的时间解决这个问题
=begin
  def new
    sign_in_page = Mechanize.new.get(SIGN_UP_URI)
    @image_url = sign_in_page.search("img.rucaptcha-image")[0].attr('src')
    if params[:user_login] && params[:user_name] && params[:user_email] && params[:user_password] && params[:user_password_confirmation] && params[:captcha]
      sign_in_form = sign_in_page.forms.last
      sign_in_form.fields[1].value = params[:user_login]
      sign_in_form.fields[2].value = params[:user_name]
      sign_in_form.fields[3].value = params[:user_email]
      sign_in_form.fields[5].value = params[:user_password]
      sign_in_form.fields[6].value = params[:user_password_confirmation]
      sign_in_form.fields[7].value = params[:captcha]
      signed_page = sign_in_form.submit
    end
  end
=end

  def create
    begin
      params[:notice] = [] #用来记录注册后的返回信息
      sign_in_form = $page.forms.last  #注册页面只有搜索和用户注册两个表单，所以取最后一个表单
      #插入相应值
      sign_in_form.fields[1].value = params[:user_login]
      sign_in_form.fields[2].value = params[:user_name]
      sign_in_form.fields[3].value = params[:user_email]
      sign_in_form.fields[5].value = params[:user_password]
      sign_in_form.fields[6].value = params[:user_password_confirmation]
      sign_in_form.fields[7].value = params[:captcha]
      #向Ruby China提交表单
      signed_page = sign_in_form.submit
      logger.info signed_page.body
      #将返回的页面body元素赋于params[:notice]方便index显示注册成功或者失败的消息
      params[:notice] << signed_page.body
      render :index
    rescue => e
      render :new
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  BASIC_TOPICS_URI = 'https://ruby-china.org/topics?page='
  BASIC_COMMENTS_URI = 'https://ruby-china.org/topics/'

  def index
  end

  def show_topics
    page = params[:page].to_i
    uri = BASIC_TOPICS_URI + page.to_s
    @topics = Mechanize.new.get(uri).search("div#main div.title a").to_a
    @users = Mechanize.new.get(uri).search("div#main div.info a").to_a
    @hrefs = Mechanize.new.get(uri).search("div#main div.title a").to_a
  end

  def show_comments
    topic_id = params[:topic_id]
    uri = BASIC_COMMENTS_URI + topic_id
    @comment_authors = Mechanize.new.get(uri).search("div#replies span.name a").to_a
    @comment_contents = Mechanize.new.get(uri).search("div#replies div.markdown p").to_a
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiandianchengTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<p><%= params[:notice][0] %></p>

app/views/users/new.html.erb
<h1>Ruby China用户注册</h1>
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<%=form_tag users_path, method: :post do%>
    <p>
        <label>用户名:</label>
        <%= text_field_tag('user_login', nil, placeholder: "用户名", required: true) %>
    </p>
    <p>
        <label>名字:</label>
        <%= text_field_tag('user_name', nil, placeholder: "名字", required: true) %>
    </p>
    <p>
        <label>Email:</label>
        <%= text_field_tag('user_email', nil, placeholder: "Email", required: true) %>
    </p>
    <p>
        <label>密码:</label>
        <%= password_field_tag('user_password', nil, placeholder: "密码", required: true) %>
    </p>
    <p>
        <label>确认密码:</label>
        <%= password_field_tag('user_password_confirmation', nil, placeholder: "确认密码", required: true) %>
    </p>
    <p>
        <label>验证码:</label>
        <%= text_field_tag('captcha', nil, placeholder: "验证码", required: true) %>
    </p>
    <p><img src=<%= @image_url %>></p>
    <button type="submit">提交</button>
<% end %>
<%= link_to "返回首页", "/" %>

app/views/welcome/index.html.erb
<h1>Ruby China</h1>
<p>获取Ruby China社区话题</p>
<p>请输入您想要获取Ruby China话题板块相应页的页码</p>
<%=form_tag welcome_show_topics_path, method: :get do%>
    <label>页码:</label>
    <%= text_field_tag('page', nil, placeholder: "请填写想要获取的页码值", required: true) %>
    <button type="submit">提交</button>
<% end %>

<p><%= link_to "注册", new_user_path %></p>
<p><%= link_to "登录", new_session_path %></p>

app/views/welcome/show_comments.html.erb
<h1>话题评论</h1>
<table>
    <thead>
        <tr>
            <th>评论者</th>
            <th>评论内容</th>
        </tr>
    </thead>
    <tbody>
        <% (0..@comment_authors.length-1).each do |i| %>
            <tr>
                <td><%= @comment_authors[i].text %></td>
                <td><%= @comment_contents[i].text %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/welcome/show_topics.html.erb
<h1>Ruby China话题</h1>
<table>
    <thead>
        <tr>
            <th>话题发起者</th>
            <th>话题</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        <% (0..@topics.length-1).each do |i| %>
            <tr>
                <td><%= @users[i].text %></td>
                <td><%= @topics[i].text %></td>
                <td><%= link_to "查看评论内容", welcome_show_comments_path(topic_id: @hrefs[i].attr("href").split('/').last.to_i) %></td>
            </tr>
        <% end %>
    </tbody>
</table>